### ISSUE TITLE
Website Redesign: "Get Involved" Page 3- Roadmap/ Memorandum- Links

### ISSUE THREAD

**Issue by UXBrendan** [orcasound/orcahome#108]
_**User Story**_
AS an Orcahome user I WANT to select links on the Get Involved page SO THAT I can navigate to webpages that the links point to.

**_Description_**
The intent of this story is to link all hypertext links, buttons, and images on the Get Involved page for the Roadmap and Memorandum sections so that they are functional.

**_NOTES:_**
     **Links**
          **Memorandum of Agreements**
- [ ] "2016-2020 Memorandum of Agreements (MOA)" hypertext link: https://docs.google.com/document/d/1OdKOICgPNHy7CkaHjzWMztH_zNir4UlbZbOdKtyRwI0/edit?usp=sharing
- [ ]"info@orcasound.net": Email to:info@orcasound.net link

          **Current Roadmap**
- [ ] "Orcasound project at DemocracyLab" hypertext link: https://www.democracylab.org/projects/81
- [ ] "Orcasound Slack" hypertext link: https://orcasound.slack.com/
- [ ] "Github repositories" hypertext link: https://github.com/orgs/orcasound/repositories
- [ ] "Trello boards" hypertext link: https://trello.com/w/hydrophonenetwork/home
- [ ] "Orcasound dev email distribution list" hypertext link: http://lists.orcasound.net/listinfo.cgi/dev-orcasound.net
- [ ] "Orcasound Hacker Hall of Fame": https://www.orcasound.net/hacker-hall-of-fame/
     - Subject to change, but works for now
- [ ] Current road map image
     - [ ] Upon selection of the image, please expand image and allow user to zoom in and out to see image in better detail
          - [ ] If elements of image zooming need to be designed by the UX Team or you have questions regarding expansion and zoom features, please tag @UXBrendan in comments in this issue for any additional information needed
- [ ] "LEARN MORE ABOUT VOLUNTEERING" button: https://www.orcasound.net/support/
     - Subject to change, but works for now

          **Other**
- [ ] Please double check all instances of "Orcasound"- text should always have a lower case s, never "OrcaSound"

**_Acceptance Criteria_**
GIVEN I see the Orcasound Get Involved page hypertext links, buttons, and images WHEN I select the hypertext links, buttons, and images in the page THEN I am taken to the correct target webpages and see expanded image.

Current road map design in Figma file for reference: https://www.figma.com/file/YdvbAjHETokV2x1LBHaElj?node-id=860:2526#409937693
Memorandum of Agreements in Figma file for reference: https://www.figma.com/file/YdvbAjHETokV2x1LBHaElj?node-id=860:2526#409938379

**Comment by NayoBaez** [comment]
@UXBrendan All links included / Image zoom is implemented with the Next.js zoom dependency, not a huge fan but we can discuss it on Monday / Orcasound capitalisation checked! Did I forget anything?

**Comment by UXBrendan** [comment]
@NayoBaez 

Thanks! I think it's all good, but now that I know how to review UI in PRs, I may reach back out for updates. Thanks for all your hard work on this!

**Comment by UXBrendan** [comment]
@NayoBaez 

I would like to discuss how to best write issues and assign to Orcasound devs to do some clean up production work for Orcahome. We're in the home stretch!

Orcasound: Dev discussion for Orcahome
Thursday, September 14 · 10:00 – 11:00am
Time zone: America/Los_Angeles
Google Meet joining info
Video call link: https://meet.google.com/vxp-aeto-zev
